//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagonoteToolkitForEmbedded.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagonoteToolkitForEmbedded.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   See the following URL for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoLibrariesBody {
            get {
                return ResourceManager.GetString("AboutInfoLibrariesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Libraries used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoLibrariesTitle {
            get {
                return ResourceManager.GetString("AboutInfoLibrariesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software is licensed under the MIT License.
        ///See the following URL for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoLicenseBody {
            get {
                return ResourceManager.GetString("AboutInfoLicenseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoLicenseTitle {
            get {
                return ResourceManager.GetString("AboutInfoLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoProductTitle {
            get {
                return ResourceManager.GetString("AboutInfoProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutInfoVersionTitle {
            get {
                return ResourceManager.GetString("AboutInfoVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magonote Toolkit For Embedded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AboutInfo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAboutInfo {
            get {
                return ResourceManager.GetString("MenuAboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuConversion {
            get {
                return ResourceManager.GetString("MenuConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generation(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGeneration {
            get {
                return ResourceManager.GetString("MenuGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCU&amp;IC(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuMcuIc {
            get {
                return ResourceManager.GetString("MenuMcuIc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AboutInfo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubTitleAboutInfo {
            get {
                return ResourceManager.GetString("SubTitleAboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This toolkit is a collection of useful tools for embedded software development.
        ///Please select a tool from the menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeMessageBody {
            get {
                return ResourceManager.GetString("WelcomeMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to &quot;Magonote Toolkit For Embedded&quot;! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeMessageTitle {
            get {
                return ResourceManager.GetString("WelcomeMessageTitle", resourceCulture);
            }
        }
    }
}
