//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagonoteToolkitForEmbedded.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagonoteToolkitForEmbedded.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddDefinition {
            get {
                return ResourceManager.GetString("AddDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfterDefinition {
            get {
                return ResourceManager.GetString("AfterDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfterValue {
            get {
                return ResourceManager.GetString("AfterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magonote Toolkit For Embedded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeforeDefinition {
            get {
                return ResourceManager.GetString("BeforeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeforeValue {
            get {
                return ResourceManager.GetString("BeforeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeDefinition {
            get {
                return ResourceManager.GetString("ChangeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckDisabled {
            get {
                return ResourceManager.GetString("CheckDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckEnabled {
            get {
                return ResourceManager.GetString("CheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare C language defines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompareClangDefines {
            get {
                return ResourceManager.GetString("CompareClangDefines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CountClear {
            get {
                return ResourceManager.GetString("CountClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CountUp {
            get {
                return ResourceManager.GetString("CountUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteDefinition {
            get {
                return ResourceManager.GetString("DeleteDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Important notice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionOptions {
            get {
                return ResourceManager.GetString("InspectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionResult {
            get {
                return ResourceManager.GetString("InspectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionTarget {
            get {
                return ResourceManager.GetString("InspectionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Libraries used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line feed code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCode {
            get {
                return ResourceManager.GetString("LineFeedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mixed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCodeMixed {
            get {
                return ResourceManager.GetString("LineFeedCodeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only &quot;CR&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCodeOnlyCR {
            get {
                return ResourceManager.GetString("LineFeedCodeOnlyCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only &quot;CR+LF&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCodeOnlyCRLF {
            get {
                return ResourceManager.GetString("LineFeedCodeOnlyCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only &quot;LF&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCodeOnlyLF {
            get {
                return ResourceManager.GetString("LineFeedCodeOnlyLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineFeedCodeUnknown {
            get {
                return ResourceManager.GetString("LineFeedCodeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comparison(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuComparison {
            get {
                return ResourceManager.GetString("MenuComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuConversion {
            get {
                return ResourceManager.GetString("MenuConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generation(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGeneration {
            get {
                return ResourceManager.GetString("MenuGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection(_I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuInspection {
            get {
                return ResourceManager.GetString("MenuInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCU&amp;IC(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuMcuIc {
            get {
                return ResourceManager.GetString("MenuMcuIc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuMeasurement {
            get {
                return ResourceManager.GetString("MenuMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   See the following URL for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAboutInfoLibrariesBody {
            get {
                return ResourceManager.GetString("MessageAboutInfoLibrariesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software is licensed under the MIT License.
        ///See the following URL for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAboutInfoLicenseBody {
            get {
                return ResourceManager.GetString("MessageAboutInfoLicenseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageComplete {
            get {
                return ResourceManager.GetString("MessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A fatal error has occurred.
        ///Termination this application.
        ///========== more information: ========== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFieldIsRequired {
            get {
                return ResourceManager.GetString("MessageFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFolderNotFound {
            get {
                return ResourceManager.GetString("MessageFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1][2][3][4][5]:Select counter | [W]:Count up | [S]:Count down | [BackSpace]:Count clear
        ///numpad [1][2][3][4][5]:Select counter | [+]:Count up | [-]:Count down | [0]:Count clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHelpTallyCounter {
            get {
                return ResourceManager.GetString("MessageHelpTallyCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageProcessing {
            get {
                return ResourceManager.GetString("MessageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support only &quot;Shift_JIS&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSupportOnlyShiftJIS {
            get {
                return ResourceManager.GetString("MessageSupportOnlyShiftJIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This toolkit is a collection of useful tools for embedded software development.
        ///Please select a tool from the menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWelcomeBody {
            get {
                return ResourceManager.GetString("MessageWelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to &quot;Magonote Toolkit For Embedded&quot;! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWelcomeTitle {
            get {
                return ResourceManager.GetString("MessageWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newline at EOF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewlineAtEOF {
            get {
                return ResourceManager.GetString("NewlineAtEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   N/A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultNA {
            get {
                return ResourceManager.GetString("ResultNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultNG {
            get {
                return ResourceManager.GetString("ResultNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultOK {
            get {
                return ResourceManager.GetString("ResultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AboutInfo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewTitleAboutInfo {
            get {
                return ResourceManager.GetString("ViewTitleAboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Definition comparison に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewTitleComparisonDefinition {
            get {
                return ResourceManager.GetString("ViewTitleComparisonDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File inspection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewTitleFileInspection {
            get {
                return ResourceManager.GetString("ViewTitleFileInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tally counter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewTitleTallyCounter {
            get {
                return ResourceManager.GetString("ViewTitleTallyCounter", resourceCulture);
            }
        }
    }
}
